### ISSUE TITLE
Research on how to improve our model

### ISSUE THREAD

**Issue by remonechev** [jessekentwang/Kaggle-Santander#10]

**Comment by jessekentwang** [comment]
See “Feature Importance v1” by Heiko

df_features.corr()[‘renta’].sort_values() 
	finds features most correlated with ‘renta’
Can find median and replace. 

“Comprehensive exploration and Visualization”
There are some customers with seniority less than zero. I will replace with 0
df[df["antiguedad"]<0] = 0
1. Prepare dataset – use accounts as features as well!
2. Subset data just May and June
3. train on May, test on June

Algorithms – Use Naive Bayes

Feature idea: number of accounts person currently has
Feature idea: how long ago account was opened
Feature idea: whether account was cancelled or just you never had it

Look into: Is the random forest reading categorical features as numerical or vice versa?
Reduce dataset, genetic algorithm?

**Comment by remonechev** [comment]
Sreejan found function to visualize actual score (mapk)


Unique ncodpers = 956645
Training dataset shape = (13647309, 48)


Jesse: Creating a feature that indicates how many accounts a person has.
Raul:  Ideas for new feature tracking whether a product is newly acquired, maintained or dropped.
https://www.kaggle.com/apryor6/santander-product-recommendation/detailed-cleaning-visualization-python/comments -

**Comment by remonechev** [comment]
raulm17 [8:16 PM]  
https://www.kaggle.com/c/santander-product-recommendation/forums/t/25871/naive-bayes-genetic-algorithms-lb-0-0272-cleaned-and-reduced-dataset-included
 kaggle.com
Naive Bayes + Genetic Algorithms-> LB 0.0272 (Cleaned and reduced dataset included) - Santander Product Recommendation | Kaggle
